# Model gateway (OpenAI-compatible) settings
openai:
  base_url: "https://www.example.com/openai/deployments/xyz-gpt-4.1-2025-04-14"
  api_version: "2024-10-21"
  oauth:
    token_url: "https://www.example.com/oauth2/v1/token"
    token_scope: "http://www.example.com/v1/scope"

# oci generative AI settings
oci:
  model_id: "ocid1.generativeaimodel.oc1.us-chicago-1.xxxxx"
  service_endpoint: "https://inference.generativeai.us-chicago-1.oci.oraclecloud.com"
  compartment_id: "ocid1.tenancy.oc1..yyyyy"
  auth_type: "API_KEY"
  auth_profile: "zzzzz"
  model_kwargs:
    temperature: 0
    top_p: 0.75
    max_tokens: 512

# Local model settings
local:
  model_id: "qwen2.5:14b"
